CREATE TABLE "tb_user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" bytea NOT NULL,
  "salt" bytea NOT NULL,
  "role_id" integer NOT NULL,
  "active" bool NOT NULL,
  "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE "tb_role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL
);

ALTER TABLE "tb_user" ADD FOREIGN KEY ("role_id") REFERENCES "tb_role" ("id");
